# https://taskfile.dev

version: "3"

vars:
  CRNAME: "{{.NAME}}"

tasks:
  default:
    desc: "Show available commands"
    cmds:
      - task -a
    silent: true

  add-rustfmt:
    desc: "Initialize project"
    cmds:
      - rustup default stable
      - rustup component add rustfmt

  fmt:
    desc: "Format the code"
    cmds:
      - cargo fmt

  new-lib:
    desc: "Create a new rust library"
    cmds:
      - cargo new --lib {{.CRNAME}}

  new-bin:
    desc: "Create new rust binary"
    cmds:
      - cargo new {{.CRNAME}}

  run-tests:
    desc: "Run rust tests"
    cmds:
      - cargo test

  init-libs:
    desc: "Setup all libraries"
    cmds:
      - cargo new --lib utils

  run:
    desc: "Run binary"
    cmds:
      - cargo run -p {{.CRNAME}}
